version: '3'
services:

  flask:
    build:
      context: .
      dockerfile: DockerfileServer
    ports:
      - 5000:5000
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: DockerfileFrontend
      args:
        REACT_APP_BACKEND_URL: http://localhost:5000
    ports:
      - 80:80
    restart: unless-stopped


# networks:
#   default:
#     external:
#       name: dockerInternal

